remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Prova del sito finale
description: con questa descrizione
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
